version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-29
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Compile Instrumentation test
          command: ./gradlew assembleAndroidTest
      - run:
          name: Compile build
          command: ./gradlew build